### PR TITLE
Correct typos

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by jstac** [comment]
Hi @gliptak, I'm on holiday and away from my computer so @mmcky will help with these PRs.  

But they are appreciated, thanks.

**Comment by mmcky** [comment]
Hi @gliptak thanks for these PR's. They are appreciated. This repository is a collection of notebooks that are **generated** by the source repository:

https://github.com/QuantEcon/lecture-source-py

It would be helpful if you could add any pickups (as PR's) to that repository as it will then flow through to this repository when we update the collection of notebooks generated from the source `rst` files.

**Comment by mmcky** [comment]
the `README` is inadequate for this repo -- so I will update it today to include that information.

**Comment by gliptak** [comment]
@mmcky thank you. I didn't connect the flow

**Pull request closed without merging**
