### PR TITLE
scipy: Return value in bisect(), replace deprecated normed kwarg with density, and set random seed

### PR DESCRIPTION
**Pull request by MaxGhenis**
This makes three changes:
1. Return the result in the `bisect` in the solution at the end. User pyanni noted that the current solution doesn't return anything in https://discourse.quantecon.org/t/scipy-lecture-question-1-recursive-function/528. In making this change and reviewing the diff I noticed two other things that could be improved, and made changes accordingly:
2. Replace the deprecated `normed` kwarg in `hist` with `density`. This was throwing a warning.
3. Set the random number seed. The results of random number generators are different this time, but this will reduce variability when making future changes.

### CODE REVIEW

**Comment by natashawatkins** [comment]
Hi @MaxGhenis, actually to edit the lectures, you'll need to edit the rst file in `/source/rst`. We use this as it's easier to version control.

**Comment by natashawatkins** [comment]
Sorry,  the files are in another repo: https://github.com/QuantEcon/lecture-source-py

This repo is automatically generated from source files.

**Comment by natashawatkins** [comment]
However the first change isn't needed. Please feel free to implement the second change. The third change is mitigated by the fact that we only edit the inputs in the rst file, and automatically generate the output.

**Comment by MaxGhenis** [comment]
Thanks @natashawatkins, closing this to continue the three discussions elsewhere:
1. In https://discourse.quantecon.org/t/scipy-lecture-question-1-recursive-function/528/4 (can be followed with a PR in lecture-source-py if you agree)
2. PR https://github.com/QuantEcon/lecture-source-py/pull/215
3. Issue https://github.com/QuantEcon/lecture-source-py/issues/216 (makes sense that it's mitigated by automatically generated output, but I think the consistency can still benefit users)

**Pull request closed without merging**
